### ISSUE TITLE
不支持MultiDex

### ISSUE THREAD

**Issue by luxiaoyu** [xiaobo0113/MethodTimeCost#3]
运行时会报 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xiaobo.example.java_assist.TimeUtil" on path: DexPathList

**Comment by xiaobo0113** [comment]
![code](https://user-images.githubusercontent.com/22719696/33308197-62d377c2-d454-11e7-8c43-2f4b0092a17d.png)

Demo 运行没问题吧？你是怎么使用的呢？或者说你自定义了 sourceSets 的相关目录？ 

我在这个地方释放了 TimeUtil.class 到编译目录的，如果一切 ok 应该是会有这个类的，不过我确实没有给出相关的判断。

另外，你是曾经手百的那个鲁晓宇么？^_^

**Comment by xiaobo0113** [comment]
再试试呢，我提了代码，改变了一下把 TimeUtil.class 加入到 pool 的方式。成功或者失败，都请告诉我结果，谢谢！
